# Generated by Django 4.0.5 on 2022-12-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('taskname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollapp.tasks')),
            ],
        ),
    ]
