# Generated by Django 4.0.5 on 2022-12-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollapp', '0002_taskdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskhis', models.TextField(default='{}')),
            ],
        ),
    ]
